-- AI insights generated by Claude per weight class
CREATE TABLE IF NOT EXISTS ai_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  weight_class int NOT NULL,
  wrestler_name text NOT NULL,
  confidence_score int NOT NULL CHECK (confidence_score BETWEEN 0 AND 100),
  confidence_label text NOT NULL DEFAULT 'MEDIUM', -- LOW | MEDIUM | HIGH
  insight_text text,
  upset_risk text NOT NULL DEFAULT 'LOW',          -- LOW | MEDIUM | HIGH
  injury_alert bool DEFAULT false,
  injury_note text,
  generated_at timestamptz DEFAULT now()
);

-- News/injury items scraped from wrestling sources
CREATE TABLE IF NOT EXISTS news_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  url text,
  source text,           -- FloWrestling | WrestleStat | InterMat | TrackWrestling
  content text,
  wrestler_name text,
  weight_class int,
  is_injury_alert bool DEFAULT false,
  scraped_at timestamptz DEFAULT now()
);

-- Public read access (no auth required to view insights)
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read ai_insights" ON ai_insights FOR SELECT USING (true);

ALTER TABLE news_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read news_items" ON news_items FOR SELECT USING (true);

-- Index for fast weight class lookups
CREATE INDEX IF NOT EXISTS ai_insights_wc_idx ON ai_insights (weight_class);
CREATE INDEX IF NOT EXISTS ai_insights_generated_idx ON ai_insights (generated_at DESC);
CREATE INDEX IF NOT EXISTS news_items_scraped_idx ON news_items (scraped_at DESC);
